version: '3.9'
services:
  app:
    build: .
    container_name: github-tracking-tool
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

